apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysqldb
        image: mysql:latest
        ports:
         - containerPort: 3306
        volumeMounts:
        # - name: mysql-storage
        #   mountPath: /var/lib
        - name: mysql-init-script
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ROOT_PASSWORD
              name: dbsecret
        livenessProbe:
          exec:
            command:
            - bash
            - "-c"
            - |
             mysqladmin -uroot -p$MYSQL_ROOT_PASSWORD ping &> /dev/null
          initialDelaySeconds: 30
          periodSeconds: 5
        #   failureThreshold: 3
        # readinessProbe:
        #   exec:
        #     command:
        #     - "/bin/sh"
        #     - "-c"
        #     - "mysql -u root -p$MYSQL_ROOT_PASSWORD < /etc/mysql-init/mysql-init.sql"
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
      volumes:
      # - name: mysql-storage
      #   emptyDir: {}
      - name: mysql-init-script
        configMap:
          name: mysql-init-script
