apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: app
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "apt update && apt install -y mysql-client && sleep infinity"]
    env:
    - name: DATABASE_HOST
      value: mysql-service.default.svc.cluster.local
    - name: DATABASE_PORT
      value: "3306"
    - name: DATABASE_USER
      value: root
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: ROOT_PASSWORD
